[toolchain]
channel = "1.86.0"
components = [ "rustc", "cargo", "rustfmt", "rust-std", "rust-docs", "clippy", "rust-analyzer", "rust-src"]
targets = [ "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl" ]
