//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod location;
pub mod product;
pub mod recipe;
pub mod recipe_ingredients;
pub mod refill;
pub mod sea_orm_active_enums;
pub mod user;
pub mod warehouse;
pub mod warehouse_product;
pub mod warehouse_recipe;
