//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::location::Entity as Location;
pub use super::product::Entity as Product;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_ingredients::Entity as RecipeIngredients;
pub use super::refill::Entity as Refill;
pub use super::user::Entity as User;
pub use super::warehouse::Entity as Warehouse;
pub use super::warehouse_product::Entity as WarehouseProduct;
pub use super::warehouse_recipe::Entity as WarehouseRecipe;
