//! Defines the `LocationCategory` enum used in the database schema.
//!
//! This enum represents different types of location categories associated
//! with products or other entities, and is managed by SeaORM.
//!
//! `LocationCategory` is an active enum generated by `sea-orm-codegen` 0.12.15.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Represents a currency type used in the application.
/// This enum is serialized and deserialized for compatibility with external
/// systems and stored in the database as an enumerated type.
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "currency")]
pub enum Currency {
    /// The custom currency "epicoin" used within the system.
    #[sea_orm(string_value = "epicoin")]
    Epicoin,

    /// The standard currency "euro."
    #[sea_orm(string_value = "euro")]
    Euro,
}

/// Represents a unit of measurement used in the application.
///
/// This enum defines various standard units, such as grams, liters, meters, and generic units
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "unit")]
pub enum Unit {
    ///  Represents a unit of weight (grams).
    #[sea_orm(string_value = "gram")]
    Gram,
    ///  Represents a unit of volume (liters).
    #[sea_orm(string_value = "liter")]
    Liter,
    ///  Represents a unit of length (meters).
    #[sea_orm(string_value = "meter")]
    Meter,
    ///  Represents a generic unit.
    #[sea_orm(string_value = "unit")]
    Unit,
}

/// Enum representing categories for various locations.
///
/// This enum is used to classify locations into specific categories, such as
/// `Dispenser` for distribution points or `Room` for room-based locations.
/// The `LocationCategory` enum is mapped to the database as an enum type.
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "location_category")]
pub enum LocationCategory {
    /// Represents a dispenser location category.
    /// This variant corresponds to the `dispenser` string in the database.
    #[sea_orm(string_value = "dispenser")]
    Dispenser,

    /// Represents a room location category.
    /// This variant corresponds to the `room` string in the database.
    #[sea_orm(string_value = "room")]
    Room,
}
