//! Defines the `LocationCategory` enum used in the database schema.
//!
//! This enum represents different types of location categories associated
//! with products or other entities, and is managed by SeaORM.
//!
//! `LocationCategory` is an active enum generated by `sea-orm-codegen` 0.12.15.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Enum representing categories for various locations.
///
/// This enum is used to classify locations into specific categories, such as
/// `Dispenser` for distribution points or `Room` for room-based locations.
/// The `LocationCategory` enum is mapped to the database as an enum type.
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "location_category")]
pub enum LocationCategory {
    /// Represents a dispenser location category.
    /// This variant corresponds to the `dispenser` string in the database.
    #[sea_orm(string_value = "dispenser")]
    Dispenser,

    /// Represents a room location category.
    /// This variant corresponds to the `room` string in the database.
    #[sea_orm(string_value = "room")]
    Room,
}
