//! Represents the `warehouse` table in the database, generated by `sea-orm-codegen 1.0.1`.
//! Defines the structure of the `warehouse` model and its relationships.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Struct representing the `warehouse` table model in SeaORM.
/// Contains fields corresponding to the columns in the `warehouse` table.
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    proc::DeriveToFilterQuery,
    proc::DeriveToSortQuery,
)]
#[sea_orm(table_name = "warehouse")]
pub struct Model {
    /// The unique identifier for the warehouse.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// The name of the warehouse
    pub name: String,
    /// Indicates whether the warehouse is disabled.
    #[sea_orm(filter_single)]
    pub disabled: bool,
    /// Timestamp for when the warehouse was created.
    #[sea_orm(filter_override = "chrono::DateTime<chrono::Utc>", filter_plus_order)]
    pub created_at: DateTimeWithTimeZone,
}

/// Enum representing the relationships of the `warehouse` entity in SeaORM.
/// Defines how `warehouse` is related to other entities, enabling query joins.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Represent the products of this warehouse
    #[sea_orm(has_many = "super::warehouse_products::Entity")]
    WarehouseProducts,

    /// Represent the recipes of this warehouse
    #[sea_orm(has_many = "super::warehouse_recipes::Entity")]
    WarehouseRecipes,
}

impl Related<super::warehouse_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseProducts.def()
    }
}

impl Related<super::warehouse_recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseRecipes.def()
    }
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        super::warehouse_products::Relation::Product.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::warehouse_products::Relation::Warehouse.def().rev())
    }
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        super::warehouse_recipes::Relation::Recipe.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::warehouse_recipes::Relation::Warehouse.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
