//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Struct representing the `warehouse_recipes` table model in SeaORM.
/// Contains fields corresponding to the columns in the `warehouse_recipes` table.
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    proc::DeriveToFilterQuery,
    proc::DeriveToSortQuery,
)]
#[sea_orm(table_name = "warehouse_recipes")]
pub struct Model {
    /// The unique identifier for the warehouse.
    #[sea_orm(primary_key, auto_increment = false)]
    pub warehouse_id: Uuid,

    /// The unique identifier for the recipe.
    #[sea_orm(primary_key, auto_increment = false)]
    pub recipe_id: Uuid,

    /// The priority of application for warehouse recipes
    pub priority: i32,

    /// Timestamp for when the link was created.
    #[sea_orm(filter_override = "chrono::DateTime<chrono::Utc>", filter_plus_order)]
    pub created_at: DateTimeWithTimeZone,
}

/// Enum representing the relationships of the `warehouse_recipes` entity in SeaORM.
/// Defines how `warehouse` is related to other entities, enabling query joins.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Represent the recipe of this many/many relation
    #[sea_orm(
        belongs_to = "super::recipe::Entity",
        from = "Column::RecipeId",
        to = "super::recipe::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Recipe,

    /// Represent the warehouse of this many/many relation
    #[sea_orm(
        belongs_to = "super::warehouse::Entity",
        from = "Column::WarehouseId",
        to = "super::warehouse::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Warehouse,
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipe.def()
    }
}

impl Related<super::warehouse::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Warehouse.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
