//! Represents the `warehouse` table in the database, generated by `sea-orm-codegen 1.0.1`.
//! Defines the structure of the `warehouse` model and its relationships.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Struct representing the `warehouse` table model in SeaORM.
/// Contains fields corresponding to the columns in the `warehouse` table.
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    proc::DeriveToFilterQuery,
    proc::DeriveToSortQuery,
)]
#[sea_orm(table_name = "warehouse")]
pub struct Model {
    /// The unique identifier for the warehouse.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// The name of the warehouse
    pub name: String,
}

/// Enum representing the relationships of the `warehouse` entity in SeaORM.
/// Defines how `warehouse` is related to other entities, enabling query joins.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
