[package]
name = "proc"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true
name = "proc"
path = "src/lib.rs"

[dependencies]
syn = { version = "2.0.89", features = ["full"] }
quote = "1.0.37"
proc-macro2 = "1.0.92"
heck = "0.5.0"
