[package]
name = "proc"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
proc-macro = true
name = "proc"
path = "src/lib.rs"

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
heck = { workspace = true }
